services:
#    app.admin.gender:
#        class: AppBundle\Admin\GenderAdmin
#        arguments: [~, AppBundle\Entity\Gender, SonataAdminBundle:CRUD]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: User, label: Gender }